name: Test
on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Java 8 version
        run: java -version
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16-ea
      - name: Java 16 version
        run: java -version
